/**
 * process-images.js
 *
 * Walks all subfolders under public/images/, finds original JPEGs,
 * generates three WebP sizes (400, 800, 1200px wide) alongside each,
 * and auto-generates src/data/photos.js grouped by top-level space folder.
 *
 * Run with: npm run process-images
 */

import sharp from 'sharp';
import { glob } from 'glob';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const IMAGES_DIR = path.join(ROOT, 'public', 'images');
const DATA_DIR = path.join(ROOT, 'src', 'data');
const SIZES = [400, 800, 1200];
const QUALITY = 82;

// Derive a human-readable space name from a folder name
function toSpaceName(folderName) {
  return folderName
    .replace(/-/g, ' ')
    .replace(/\b\w/g, c => c.toUpperCase())
    .trim();
}

// Derive alt text from space name + filename
function toAltText(spaceName, filename) {
  const base = path.basename(filename, path.extname(filename))
    .replace(/[-_]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  return `${spaceName} - ${base}`;
}

// Convert an absolute file path to a /images/... URL path
function toUrlPath(absPath) {
  const rel = path.relative(path.join(ROOT, 'public'), absPath);
  return '/' + rel.split(path.sep).join('/');
}

async function main() {
  // Find all JPEG files recursively under public/images/
  const pattern = path.join(IMAGES_DIR, '**', '*.{jpg,jpeg,JPG,JPEG}').replace(/\\/g, '/');
  const allFiles = await glob(pattern, { nocase: true });

  // Filter out already-sized variants
  const originals = allFiles.filter(f => {
    const base = path.basename(f, path.extname(f));
    return !/-(?:400|800|1200)$/.test(base);
  });

  console.log(`Found ${originals.length} original JPEG(s) to process.\n`);

  // Track results grouped by top-level space folder
  const spaces = {};
  let photoId = 1;

  for (const srcPath of originals) {
    // Determine top-level space folder (first dir under public/images/)
    const rel = path.relative(IMAGES_DIR, srcPath);
    const parts = rel.split(path.sep);
    const spaceFolderName = parts[0];
    const spaceName = toSpaceName(spaceFolderName);

    if (!spaces[spaceFolderName]) {
      spaces[spaceFolderName] = { name: spaceName, photos: [] };
    }

    // Get original image metadata
    let metadata;
    try {
      metadata = await sharp(srcPath).metadata();
    } catch (err) {
      console.warn(`  ⚠ Skipping (cannot read): ${rel} — ${err.message}`);
      continue;
    }

    const { width: origWidth, height: origHeight } = metadata;

    // Generate WebP variants
    const dir = path.dirname(srcPath);
    const base = path.basename(srcPath, path.extname(srcPath));
    const srcSet = [];

    for (const size of SIZES) {
      // Never upscale
      if (size > origWidth) continue;

      const outName = `${base}-${size}.webp`;
      const outPath = path.join(dir, outName);

      if (fs.existsSync(outPath)) {
        console.log(`  ✓ exists: ${path.relative(ROOT, outPath)}`);
      } else {
        await sharp(srcPath)
          .resize(size, null, { withoutEnlargement: true })
          .webp({ quality: QUALITY })
          .toFile(outPath);
        console.log(`  ✔ created: ${path.relative(ROOT, outPath)}`);
      }

      srcSet.push(`${toUrlPath(outPath)} ${size}w`);
    }

    // If all sizes were skipped (very small image), skip the photo entirely
    if (srcSet.length === 0) {
      console.warn(`  ⚠ Skipping (too small): ${rel}`);
      continue;
    }

    spaces[spaceFolderName].photos.push({
      id: photoId++,
      original: toUrlPath(srcPath),
      srcSet: srcSet.join(', '),
      width: origWidth,
      height: origHeight,
      alt: toAltText(spaceName, rel),
    });
  }

  // Write src/data/photos.js
  const spacesArray = Object.values(spaces);

  const lines = [
    '// AUTO-GENERATED by scripts/process-images.js — do not edit by hand.',
    '// Re-run `npm run process-images` after adding new photos.',
    '',
    'export const spaces = [',
  ];

  for (const space of spacesArray) {
    lines.push(`  {`);
    lines.push(`    name: ${JSON.stringify(space.name)},`);
    lines.push(`    photos: [`);
    for (const p of space.photos) {
      lines.push(`      {`);
      lines.push(`        id: ${p.id},`);
      lines.push(`        original: ${JSON.stringify(p.original)},`);
      lines.push(`        srcSet: ${JSON.stringify(p.srcSet)},`);
      lines.push(`        width: ${p.width},`);
      lines.push(`        height: ${p.height},`);
      lines.push(`        alt: ${JSON.stringify(p.alt)},`);
      lines.push(`      },`);
    }
    lines.push(`    ],`);
    lines.push(`  },`);
  }

  lines.push('];');
  lines.push('');

  fs.mkdirSync(DATA_DIR, { recursive: true });
  const outFile = path.join(DATA_DIR, 'photos.js');
  fs.writeFileSync(outFile, lines.join('\n'), 'utf8');

  console.log(`\nDone. ${photoId - 1} photo(s) across ${spacesArray.length} space(s).`);
  console.log(`Generated: src/data/photos.js`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
